sqlalchemy: retry on deadlock for create_resource_type()
sqlalchemy.exc.InternalError: (psycopg2.InternalError) current transaction is aborted, commands ignored until end of transaction block
     [SQL: 'select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s'] [parameters: {'name': u'rt_c5a9affa3ef94951823f3d81d50932de'}]

Change-Id: Id77565677fddfc1d9b9edc074b8b808cfa23a1bd
(cherry picked from commit fb972acf990ce1289ae7cb08abdc475b73df2158)