Fix gnocchi build with latest setuptools
Setuptools removed deprecated APIs in easy_install:
get_script_args, get_script_header and get_writer.
The direct usage of easy_install has been deprecated
since v58.3.0, and the warnings regarding these APIs
predate that version.

This patch fix this issue by replacing direct easy_install
call easy_install.get_script_header() with
easy_install.ScriptWriter.get_header().

Build error:

AttributeError: module 'setuptools.command.easy_install'
has no attribute 'get_script_header'

Fixes gnocchixyz/gnocchi#1304