sqlalchemy: no fail if resources and type are deleted under our feet
This is a rare case, but it can happen and did in one of our unit tests
run. When listing generic resources with details, the tables of some
resource types might disappear under our feet, at least with MySQL, and
that triggers an error:

sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError)
  (1146, "Table \'test.rt_cd01a3f48e0345ebb55ac208de7b600f\' doesn\'t exist")

Change-Id: Ia7950052e06b1e2e9cc2651b04decc8d864972a7
(cherry picked from commit 34674863cc6ed75c40d61945b5518f2bed348dbe)