sqlalchemy: add missing constraint delete_resource_type()
This constraint can also be violated in certain circumstance:

    oslo_db.exception.DBReferenceError: (pymysql.err.IntegrityError)
    (1451, u'Cannot delete or update a parent row: a foreign key constraint fails (`test1070afa755f149838f0a6ddd523e68e2`.`resource_history`, CONSTRAINT `fk_resource_history_resource_type_name` FOREIGN KEY (`type`) REFERENCES `resource_type` (`name`))') [SQL: u'DELETE FROM resource_type WHERE resource_type.name = %(name)s'] [parameters: {'name': u'my_custom_resource'}]

Change-Id: Ic3eb36fcbbcdf3353e13745ba560d9c8a7b0a760