setuptools: Disable auto discovery
The latest release of setuptools 61.0 made a breaking change[1] and
because of this change 'pip install' fails with the following error.

~~
error: Multiple top-level packages discovered in a flat-layout:
['lib', 'spec', 'manifests', 'releasenotes'].
~~

Users that don't set 'packages', 'py_modules', or configuration'
are still likely to observe the auto-discovery behavior, which may
halt the build if the project contains multiple directories and/or
multiple Python files directly under the project root.

To disable auto discovery, one can do below in setup.py

~~
setuptools.setup(..,packages=[],..)
~~

or

~~
setuptools.setup(..,py_modules=[],..)
~~

[1] https://github.com/pypa/setuptools/issues/3197

(cherry picked from commit 834c6a5c7080ca94ee26f14fb07e5ade1562aee7)