sqlalchemy: retry on PostgreSQL catalog errors too
This avoids this kind of errors:

oslo_db.exception.DBError: (psycopg2.InternalError) current transaction is aborted, commands ignored until end of transaction block
 [SQL: 'select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s'] [parameters: {'name': u'rt_9e4a0e8695ef42ddae0f4ac73608b643'}]

Change-Id: I947fc74543c016cfcdf017f69b260f695702dc0a
(cherry picked from commit 7ce5051b00f681a864d3e2a0edf6020ae37e1bef)